### ISSUE TITLE
trying to run the sample program but running into an arguments issue. 

### ISSUE THREAD

**Issue by barboa91** [tomasfarias/dota-gsi#3]
```
[alex@purplearch dota-gsi]$ cargo run --bin echoslam
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/echoslam`
error: the following required arguments were not provided:
  --uri <URI>

Usage: echoslam --uri <URI>

For more information, try '--help'.
[alex@purplearch dota-gsi]$ cargo run --bin echoslam --uri "127.0.0.1:3000"
error: unexpected argument '--uri' found

  tip: to pass '--uri' as a value, use '-- --uri'

Usage: cargo run --bin [<NAME>] [ARGS]...

For more information, try '--help'.

```

Forgive me I am new to rust.  Trying to dive headfirst into some projects I want to work on.

When I try to run the sample program I am presented with the error that I need to provide a uri. But when i give a uri it say that --uri is unexpected.

I am running arch.

**Comment by tomasfarias** [comment]
The tip tells you what to do, the call should be:
```
cargo run --bin echoslam -- --uri "127.0.0.1:3000"
```
(Notice the additional `--` separating the arguments)

Basically, the argument needs to be passed to the `echoslam` binary, not `cargo run`, hence the error, as `cargo run` tries to interpret `--uri` as an argument to `cargo run`.

Another option is to just run the `echoslam` binary directly:
```
./target/debug/echoslam --uri "127.0.0.1:3000"
```
